module.exports = [
    {
        date: 'April 1',
        taxes: 0.05,
        retirement: 10,
        save: 50,
        creditcard: 0.30,
        market: 50,
        internet: 110,
        pet: 20,
        car: 300,
        insurrance: 0,
        additional: 50,
        made: true,
    },
    {
        date: 'April 3',
        taxes: 0.05,
        retirement: 0,
        save: 0,
        creditcard: 0.30,
        market: 20,
        internet: 0,
        pet: 10,
        car: 50,
        insurrance: 0,
        additional: 15,
        made: true,
    },
    {
        date: 'April 5',
        taxes: 0.05,
        retirement: 0,
        save: 50,
        creditcard: 0.70,
        market: 40,
        internet: 0,
        pet: 10,
        car: 0,
        insurrance: 0,
        additional: 30,
        made: false,
    },
    {
        date: 'April 7',
        taxes: 0.05,
        retirement: 10,
        save: 0,
        creditcard: 0.50,
        market: 80,
        internet: 0,
        pet: 20,
        car: 0,
        insurrance: 0,
        additional: 90,
        made: true,
    },
    {
        date: 'April 13',
        taxes: 0.05,
        retirement: 0,
        save: 25,
        creditcard: 0.30,
        market: 20,
        internet: 0,
        pet: 0,
        car: 30,
        insurrance: 0,
        additional: 0,
        made: false,
    },
    {
        date: 'April 17',
        taxes: 0.05,
        retirement: 0,
        save: 0,
        creditcard: 0.30,
        market: 10,
        internet: 0,
        pet: 30,
        car: 0,
        insurrance: 250,
        additional: 50,
        made: false,
    },
    {
        date: 'April 27',
        taxes: 0.05,
        retirement: 0,
        save: 10,
        creditcard: 0.30,
        market: 40,
        internet: 0,
        pet: 25,
        car: 0,
        insurrance: 0,
        additional: 150,
        made: true,
    },
    {
        date: 'May 1',
        taxes: 0.05,
        retirement: 10,
        save: 50,
        creditcard: 0.30,
        market: 50,
        internet: 110,
        pet: 20,
        car: 300,
        insurrance: 0,
        additional: 50,
        made: true,
        
    },
    {
        date: 'May 3',
        taxes: 0.05,
        save: 0,
        retirement: 0,
        creditcard: 0.30,
        market: 20,
        internet: 0,
        pet: 10,
        car: 50,
        insurrance: 0,
        additional: 15,
        made: false,
    },
    {
        date: 'May 5',
        taxes: 0.05,
        retirement: 0,
        save: 50,
        creditcard: 0.70,
        market: 40,
        internet: 0,
        pet: 10,
        car: 0,
        insurrance: 0,
        additional: 30,
        made: false,
    },
    {
        date: 'May 7',
        taxes: 0.05,
        retirement: 10,
        save: 0,
        creditcard: 0.50,
        market: 80,
        internet: 0,
        pet: 20,
        car: 0,
        insurrance: 0,
        additional: 90,
        made: false,
    },
    {
        date: 'May 13',
        taxes: 0.05,
        retirement: 0,
        save: 25,
        creditcard: 0.30,
        market: 20,
        internet: 0,
        pet: 0,
        car: 30,
        insurrance: 0,
        additional: 0,
        made: false,
    },
    {
        date: 'May 17',
        taxes: 0.05,
        retirement: 0,
        save: 0,
        creditcard: 0.30,
        market: 10,
        internet: 0,
        pet: 30,
        car: 0,
        insurrance: 250,
        additional: 50,
        made: true,
    },
    {
        date: 'May 27',
        taxes: 0.05,
        retirement: 0,
        save: 10,
        creditcard: 0.30,
        market: 40,
        internet: 0,
        pet: 25,
        car: 0,
        insurrance: 0,
        additional: 85,
        made: true,
    },
    {
        date: 'Jun 1',
        taxes: 0.05,
        retirement: 10,
        save: 50,
        creditcard: 0.30,
        market: 50,
        internet: 110,
        pet: 20,
        car: 300,
        insurrance: 0,
        additional: 50,
        made: false,
    },
    {
        date: 'Jun 3',
        taxes: 0.05,
        retirement: 0,
        save: 0,
        creditcard: 0.30,
        internet: 0,
        market: 20,
        pet: 10,
        car: 50,
        insurrance: 0,
        additional: 15,
        made: false,
    },
    {
        date: 'Jun 5',
        taxes: 0.05,
        retirement: 0,
        save: 50,
        creditcard: 0.70,
        market: 40,
        internet: 0,
        pet: 10,
        car: 0,
        insurrance: 0,
        additional: 30,
        made: false,
    },
    {
        date: 'Jun 7',
        taxes: 0.05,
        retirement: 10,
        save: 0,
        creditcard: 0.50,
        market: 80,
        internet: 0,
        pet: 20,
        car: 0,
        insurrance: 0,
        additional: 90,
        made: true,
    },
    {
        date: 'Jun 13',
        taxes: 0.05,
        retirement: 0,
        save: 25,
        creditcard: 0.30,
        market: 20,
        internet: 0,
        pet: 0,
        car: 30,
        insurrance: 0,
        additional: 0,
        made: true,
    },
    {
        date: 'Jun 17',
        taxes: 0.05,
        retirement: 0,
        save: 0,
        creditcard: 0.30,
        market: 10,
        internet: 0,
        pet: 30,
        car: 0,
        insurrance: 250,
        additional: 50,
        made: true,
    },
    {
        date: 'Jun 27',
        taxes: 0.05,
        retirement: 0,
        save: 10,
        creditcard: 0.30,
        market: 40,
        internet: 0,
        pet: 25,
        car: 0,
        insurrance: 0,
        additional: 200,
        made: false,
    },
    {
        date: 'July 1',
        taxes: 0.05,
        retirement: 10,
        save: 50,
        creditcard: 0.30,
        market: 50,
        internet: 110,
        pet: 20,
        car: 300,
        insurrance: 0,
        additional: 50,
        made: false,
    },
    {
        date: 'July 3',
        taxes: 0.05,
        retirement: 0,
        save: 0,
        creditcard: 0.30,
        internet: 0,
        market: 20,
        pet: 10,
        car: 50,
        insurrance: 0,
        additional: 15,
        made: false,
    },
    {
        date: 'July 5',
        taxes: 0.05,
        retirement: 0,
        save: 50,
        creditcard: 0.70,
        market: 40,
        internet: 0,
        pet: 10,
        car: 0,
        insurrance: 0,
        additional: 30,
        made: true,
    },
    {
        date: 'July 7',
        taxes: 0.05,
        retirement: 10,
        save: 0,
        creditcard: 0.50,
        market: 80,
        internet: 0,
        pet: 20,
        car: 0,
        insurrance: 0,
        additional: 90,
        made: true,
    },
    {
        date: 'July 13',
        taxes: 0.05,
        retirement: 0,
        save: 25,
        creditcard: 0.30,
        market: 20,
        internet: 0,
        pet: 0,
        car: 30,
        insurrance: 0,
        additional: 0,
        made: false,
    },
    {
        date: 'July 17',
        taxes: 0.05,
        retirement: 0,
        save: 0,
        creditcard: 0.30,
        market: 10,
        internet: 0,
        pet: 30,
        car: 0,
        insurrance: 250,
        additional: 50,
        made: true,

    },
    {
        date: 'July 27',
        taxes: 0.05,
        retirement: 0,
        save: 10,
        creditcard: 0.30,
        market: 40,
        internet: 0,
        pet: 25,
        car: 0,
        insurrance: 0,
        additional: 105,
        made: true,
    },

]
